### PR TITLE
[ISSUE#75] CI/CD Pipelines: use secrets

### LINKED ISSUE #75: [CI/CD Pipeline] Use secrets to store sensitive information: BASE_URL, USER_EMAIL, USER_PASSWORD in workflow
## ✏️ Description
Currently, the sensitive information such as app's URL and test user's credentials are directly visible in the [workflow file](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/.github/workflows/pw-tests.yml) instead of being protected. As discussed in our last meeting, it'd be best to use [secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow) to protect those.

## 🔧 Why We Need This
Using secrets in CI/CD pipeline is a good practice, because it:
- does not rely on data that's directly hardcoded lowering the risk of exposure,
- ensures tests are being executed securely,
- makes them available/accessible to the selected group of users only -> meaning us, members of the KawQA-z-automatu initiative! :)

## 🚀 Proposed Solution
TBA

## ✅ Issue reporting checklist

- [x ] I created a descriptive title for this issue
- [x] I checked that it hasn't been reported yet
- [x] I assigned the issue or added `help-wanted` label
- [x] I added appropriate labels

### PR DESCRIPTION
**Pull request by Slawomir-DKl**
### Scope of changes:

Replacing overt variables with secrets

## Any other comments?

This is experiment to check, if the solution will work

Before submitting Pull Request, I've ensured that:

- [x] The PR is associated with the relevant Issue before its creation.
- [ ] All new and existing tests passed
- [x] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Slawomir-DKl** [comment]
@kat-kan It looks like the solutions works and the .env file is not needed in the CI/CD pipeline. I've left one variable "USER_ID" in the env file. When you'll add this secret to GitHub, we could delete the env file from YML file.

Two tests fail due to changes in GAD. I'll try to check the changes and make necessary fixes (or report errors :) ) during the weekend

**Comment by kat-kan** [comment]
> @kat-kan It looks like the solutions works and the .env file is not needed in the CI/CD pipeline. I've left one variable "USER_ID" in the env file. When you'll add this secret to GitHub, we could delete the env file from YML file.
> 
> Two tests fail due to changes in GAD. I'll try to check the changes and make necessary fixes (or report errors :) ) during the weekend

I've just added USER_ID variable

**Comment by Slawomir-DKl** [comment]
I've changed the YML file. Hope it will work on main branch as well.

**Review by kat-kan — APPROVED** [review]
Let's check if it 💣 😄

**Pull request merged**
