### PR TITLE
[ISSUE#77] Fix attempt for conflicting eslint libraries

### LINKED ISSUE #77: [CI/CD] Investigate and fix conflicting dependency
## ✏️ Description
https://github.com/kat-kan/kawqa-gad-playwright/actions/runs/7963281922/job/21738522791

## 🛑 Current Behavior
TBA

## ✅ Problem report checklist

- [x] I created a descriptive title for this problem report
- [x] I checked that a similar issue hasn't been reported yet
- [x] I assigned the problem report or added appropriate labels

### PR DESCRIPTION
**Pull request by bugITwhisperer**
### Scope of changes
- Attempt to fix the conflicting issue between linter libraries
It's an attempt cause on my side it works as expected

### Additional, not-related changes
- added import auto-sorting plugin: `@trivago/prettier-plugin-sort-imports`,
- added IDE (VS Code) recommendations and settings file,
- updated script name, added 2 new scripts
- style: sorted imports in all files, updated formatting,
- code: fix issues raised by linter

---
Before submitting Pull Request, I've ensured that:

- [X] The PR is associated with the relevant Issue before its creation.
- [X] All new and existing tests passed
- [X] My commit messages follow the `kawqa-gad-playwright` project's [git commit message format](https://github.com/kat-kan/kawqa-gad-playwright/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bugITwhisperer** [comment]
Conflicting libraries issue fixed. However we have 2 tests failing due to incorrect typing - might be an actual, intended bug. @kat-kan , @Justyna-KO : when reviewing the changes pls check you use the latest GAD version :)

**Comment by Justyna-KO** [comment]
> Conflicting libraries issue fixed. However we have 2 tests failing due to incorrect typing - might be an actual, intended bug. @kat-kan , @Justyna-KO : when reviewing the changes pls check you use the latest GAD version :)


"npm run lint" script works:
image

Script "npm run style" also works.

**Review by kat-kan — APPROVED** [review]
I also confirm that it works for me
As for the failing tests, I will try to investigate it...soon.. :)

**Comment by bugITwhisperer** [comment]
@kat-kan, @Justyna-KO: thanks for checking! 🙏🏻  I merged the changes :)

**Pull request merged**
